# Generated by Django 5.1.6 on 2025-03-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingDetails',
        ),
    ]
